# backend/core/vocabulario_obra.py

SINONIMOS_CANTEIRO = {
    "bobcat": "minicarregadeira",
    "brita zero": "pedrisco",
    "po de pedra": "pedrisco",
    "pó de pedra": "pedrisco",
    "munck": "guindauto",
    "muck": "guindauto",
    "caminhão munck": "caminhao carroceria com guindauto",
    "caminhao munck": "caminhao carroceria com guindauto",
    "retro": "retroescavadeira",
    "pc": "escavadeira hidraulica",
    "escavadeira pc": "escavadeira hidraulica",
    "martelete": "martelo rompedor",
    "sapinho": "compactador de solos",
    "placa vibratoria": "placa compactadora",
    "wacker": "compactador de solos",
    "betoneira": "betoneira",
    "jerica": "carrinho de mao",
    "girica": "carrinho de mao",
    "vibrador": "vibrador de imersao",
    "mangote": "vibrador de imersao",
    "makita": "serra marmore",
    "lixadeira": "esmerilhadeira",
    "policorte": "serra de corte",
    "serra circular": "serra circular",
    "furadeira": "furadeira",
    "parafusadeira": "parafusadeira",
    "compressor": "compressor de ar",
    "andaime": "andaime",
    "balancim": "andaime suspenso",
    "jaú": "andaime suspenso",
    "cadeirinha": "cadeira suspensa",
    "cinto": "cinto de seguranca",
    "talabarte": "talabarte",
    "capacete": "capacete de seguranca",
    "botina": "botina de seguranca",
    "luva": "luva de seguranca",
    "oculos": "oculos de seguranca",
    "protetor auricular": "protetor auditivo",
    "abafador": "protetor auditivo",
    "mascara": "respirador",
    "respirador": "respirador",
    "capa de chuva": "vestimenta de seguranca",
    "uniforme": "vestimenta de trabalho",
    "cabo de aço": "cabo de aco",
    "corda": "corda",
    "lona": "lona",
    "madeirite": "chapa compensado",
    "compensado": "chapa compensado",
    "tabua": "tabua",
    "sarrafo": "sarrafo",
    "pontalete": "pontalete",
    "prego": "prego",
    "arame": "arame",
    "ferro": "aco",
    "vergalhao": "aco",
    "estribo": "estribo",
    "tela": "tela",
    "cimento": "cimento",
    "areia": "areia",
    "brita": "brita",
    "pedra": "pedra",
    "bloco": "bloco",
    "tijolo": "tijolo",
    "telha": "telha",
    "cumeeira": "cumeeira",
    "calha": "calha",
    "rufo": "rufo",
    "cano": "tubo",
    "tubo": "tubo",
    "conexoes": "conexao",
    "registro": "registro",
    "valvula": "valvula",
    "torneira": "torneira",
    "sifao": "sifao",
    "ralo": "ralo",
    "grelha": "grelha",
    "caixa d'agua": "reservatorio",
    "fio": "cabo",
    "cabo": "cabo",
    "disjuntor": "disjuntor",
    "tomada": "tomada",
    "interruptor": "interruptor",
    "lampada": "lampada",
    "luminaria": "luminaria",
    "quadro": "quadro",
    "eletroduto": "eletroduto",
    "conduite": "eletroduto",
    "conduíte": "eletroduto",
    "mangueira": "mangueira",
    "tinta": "tinta",
    "massa": "massa",
    "selador": "selador",
    "verniz": "verniz",
    "thinner": "solvente",
    "aguarras": "solvente",
    "pincel": "trincha",
    "rolo": "rolo",
    "lixa": "lixa",
    "espatula": "espatula",
    "desempenadeira": "desempenadeira",
    "colher": "colher de pedreiro",
    "prumo": "prumo",
    "nivel": "nivel",
    "trena": "trena",
    "esquadro": "esquadro",
    "linha": "linha",
    "pa": "pa",
    "enxada": "enxada",
    "picareta": "picareta",
    "cavadeira": "cavadeira",
    "carrinho": "carrinho",
    "balde": "balde",
    "vassoura": "vassoura",
    "rodo": "rodo"
}
